Added my name and id
aniket-spidey/Hacktoberfest-Feedback pull request #8
Opened 2020-10-10 14:58 UTC by T232616

2020-10-10 15:17 UTC, parikshitgupta1 requested changes
make sure you have added your feedback

2020-10-11 04:15 UTC, T232616 commented
Added my name and ID to the given template

2020-10-16 19:42 UTC, parikshitgupta1 requested changes
please make sure you have given your feedback between the quotes.

2020-10-24 08:04 UTC, T232616 commented
"Added my name and ID to the given template"

2020-10-24 08:08 UTC, parikshitgupta1 requested changes
you haven't added the feedback yet!

2020-10-24 08:08 UTC, parikshitgupta1 commented on tejasjhamnani.py
> +print("Enter feedback between the quotes!")
Please enter your feedback in the given space!  @T232616

2020-10-24 08:10 UTC, ParvMarwaha commented
Hey this is parv and not tejas


On Sat, Oct 24, 2020 at 1:38 PM Parikshit Gupta <notifications@github.com>
wrote:

> *@parikshitgupta1* requested changes on this pull request.
>
> you haven't added the feedback yet!
> ------------------------------
>
> In tejasjhamnani.py
> <https://github.com/aniket-spidey/Hacktoberfest-Feedback/pull/8#discussion_r511335362>
> :
>
> > @@ -0,0 +1,3 @@
> +# Tejas Jhamnani
> +# #HF99342
> +print("Enter feedback between the quotes!")
>
> Please enter your feedback in the given space! @T232616
> <https://github.com/T232616>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/aniket-spidey/Hacktoberfest-Feedback/pull/8#pullrequestreview-516228232>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARHUFBFL5XL5KR4XNJ2Z3Q3SMKDPHANCNFSM4SLDULPA>
> .
>

2020-10-24 09:11 UTC, parikshitgupta1 reviewed
thankyou

2020-10-24 09:11 UTC, merged